In [2]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
np.random.seed(42)
n_transactions=200

# Génération des données brutes
dates = [datetime(2024, 1, 1) + timedelta(days=np.random.randint(0, 90)) for _ in range(n_transactions)]

data = {
    'transaction_id': list(range(1001, 1001 + n_transactions)),
    'date': dates,
    'montant': np.random.uniform(-5000, 10000, n_transactions).round(2),
    'categorie': np.random.choice(['Alimentation', 'Transport', 'Loisirs', 'Salaire', '???', '', None], n_transactions),
    'description': [f"ACHAT {np.random.choice(['CARREFOUR', 'UBER', 'NETFLIX', 'SALAIRIE', ''])}" for _ in range(n_transactions)],
    'type_client': np.random.choice(['particulier', 'pro', 'particulier', 'particulier', None], n_transactions),
    'devise': np.random.choice(['EUR', 'EUR', 'EUR', 'USD', 'GBP', ''], n_transactions)
}

df = pd.DataFrame(data)

In [5]:
df.info() #Types, Valeur non nulles.
df.describe() #Stats sur colonnes numeriques
df.isnull().sum() #Comptage des valeur null.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  200 non-null    int64
 1   date            200 non-null    datetime64[ns]
 2   montant         200 non-null    float64
 3   categorie       176 non-null    object
 4   description     200 non-null    object
 5   type_client     160 non-null    object
 6   devise          200 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 11.1+ KB

transaction_id     0
date               0
montant            0
categorie         24
description        0
type_client       40
devise             0
dtype: int64

In [12]:
df.duplicated().sum()
df.drop_duplicates()
df.drop_duplicates(subset=["categorie"]) # Sur colonne specifiques

,transaction_id,date,montant,categorie,description,type_client,devise
0,1001,2024-02-21,2458.73,Alimentation,ACHAT NETFLIX,pro,GBP
1,1002,2024-01-15,-486.83,,ACHAT,pro,USD
3,1004,2024-03-01,-4446.70,???,ACHAT UBER,pro,GBP
4,1005,2024-01-21,4143.47,None,ACHAT SALAIRIE,None,EUR
5,1006,2024-03-23,2540.19,Transport,ACHAT UBER,particulier,EUR
9,1010,2024-03-28,-1406.57,Salaire,ACHAT CARREFOUR,particulier,USD
15,1016,2024-03-28,6424.29,Loisirs,ACHAT SALAIRIE,particulier,EUR

In [14]:
# Remplace toutes les valeurs vides du DataFrame par 0
df["montant"]=df["categorie"].fillna("vide")

In [15]:
df

,transaction_id,date,montant,categorie,description,type_client,devise
0,1001,2024-02-21,Alimentation,Alimentation,ACHAT NETFLIX,pro,GBP
1,1002,2024-01-15,,,ACHAT,pro,USD
2,1003,2024-03-12,,,ACHAT,particulier,USD
3,1004,2024-03-01,???,???,ACHAT UBER,pro,GBP
4,1005,2024-01-21,vide,None,ACHAT SALAIRIE,None,EUR

In [18]:
df_montant=df[df["montant"]=="???"]

In [24]:
df['montant'] = df['montant'].fillna(0)

In [26]:
df

,transaction_id,date,montant,categorie,description,type_client,devise
0,1001,2024-02-21,Alimentation,Alimentation,ACHAT NETFLIX,pro,GBP
1,1002,2024-01-15,,,ACHAT,pro,USD
2,1003,2024-03-12,,,ACHAT,particulier,USD
3,1004,2024-03-01,???,???,ACHAT UBER,pro,GBP
4,1005,2024-01-21,vide,None,ACHAT SALAIRIE,None,EUR
...,...,...,...,...,...,...,...
195,1196,2024-03-02,vide,None,ACHAT,particulier,EUR
196,1197,2024-02-27,Loisirs,Loisirs,ACHAT CARREFOUR,None,EUR
197,1198,2024-02-21,Transport,Transport,ACHAT,particulier,USD
198,1199,2024-01-12,Transport,Transport,ACHAT CARREFOUR,None,USD
199,1200,2024-02-08,Loisirs,Loisirs,ACHAT SALAIRIE,None,GBP