In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [2]:
np.random.seed(42)
n_transactions=500

In [16]:
#dates=[datetime(2024, 1, 1)+ timedelta(days=np.random.randint(0,90)) for _ in range(n_transactions)]

In [23]:
# Génération des données brutes
dates = [datetime(2024, 1, 1) + timedelta(days=np.random.randint(0, 90)) for _ in range(n_transactions)]

data = {
    'transaction_id': list(range(1001, 1001 + n_transactions)),
    'date': dates,
    'montant': np.random.uniform(-5000, 10000, n_transactions).round(2),
    'categorie': np.random.choice(['Alimentation', 'Transport', 'Loisirs', 'Salaire', '???', '', None], n_transactions),
    'description': [f"ACHAT {np.random.choice(['CARREFOUR', 'UBER', 'NETFLIX', 'SALAIRIE', ''])}" for _ in range(n_transactions)],
    'type_client': np.random.choice(['particulier', 'pro', 'particulier', 'particulier', None], n_transactions),
    'devise': np.random.choice(['EUR', 'EUR', 'EUR', 'USD', 'GBP', ''], n_transactions)
}

df = pd.DataFrame(data)

In [24]:
df.head(5)

,transaction_id,date,montant,categorie,description,type_client,devise
0,1001,2024-01-22,1430.88,None,ACHAT NETFLIX,pro,EUR
1,1002,2024-03-27,-2264.97,Loisirs,ACHAT CARREFOUR,particulier,EUR
2,1003,2024-02-18,9134.51,???,ACHAT UBER,particulier,
3,1004,2024-03-08,6326.02,Salaire,ACHAT CARREFOUR,particulier,EUR
4,1005,2024-01-15,-1879.63,Loisirs,ACHAT UBER,particulier,EUR

In [26]:
#Recuperer une  section du dataframe.
df.loc[0:3, 'description']=np.nan

In [30]:
df.head(10)

,transaction_id,date,montant,categorie,description,type_client,devise
0,1001,2024-01-22,1430.88,None,NaN,pro,EUR
1,1002,2024-03-27,-2264.97,Loisirs,NaN,particulier,EUR
2,1003,2024-02-18,9134.51,???,NaN,particulier,
3,1004,2024-03-08,6326.02,Salaire,NaN,particulier,EUR
4,1005,2024-01-15,-1879.63,Loisirs,ACHAT UBER,particulier,EUR
5,1006,2024-03-05,65.66,Transport,ACHAT NETFLIX,None,USD
6,1007,2024-02-23,7145.11,Transport,ACHAT,None,GBP
7,1008,2024-01-30,5435.16,Salaire,ACHAT SALAIRIE,None,USD
8,1009,2024-01-20,6486.76,Alimentation,ACHAT NETFLIX,particulier,EUR
9,1010,2024-02-02,1618.02,Alimentation,ACHAT UBER,pro,EUR

In [35]:
df.loc[6:9, 'montant']=9999.9 #Valeur Aberrantes.

In [36]:
df.head(10)

,transaction_id,date,montant,categorie,description,type_client,devise
0,1001,2024-01-22,1430.88,None,NaN,pro,EUR
1,1002,2024-03-27,-2264.97,Loisirs,NaN,particulier,EUR
2,1003,2024-02-18,9134.51,???,NaN,particulier,
3,1004,2024-03-08,6326.02,Salaire,NaN,particulier,EUR
4,1005,2024-01-15,-1879.63,Loisirs,ACHAT UBER,particulier,EUR
5,1006,2024-03-05,65.66,Transport,ACHAT NETFLIX,None,USD
6,1007,2024-02-23,9999.90,Transport,ACHAT,None,GBP
7,1008,2024-01-30,9999.90,Salaire,ACHAT SALAIRIE,None,USD
8,1009,2024-01-20,9999.90,Alimentation,ACHAT NETFLIX,particulier,EUR
9,1010,2024-02-02,9999.90,Alimentation,ACHAT UBER,pro,EUR

In [38]:
df.loc[20, 'date']=pd.NaT # Modifier sur une ligne sur la colonne 'date'.

In [39]:
df.loc[20] #Recuperer le detail d'une ligne.

transaction_id              1021
date                         NaT
montant                  6426.14
categorie
description       ACHAT SALAIRIE
type_client          particulier
devise
Name: 20, dtype: object

In [41]:
df.loc[9, 'montant']=1000.1

In [43]:
df.loc[80:85, 'devise']='CHF' #Devise étrangere.

In [44]:
df.loc[80:85]

,transaction_id,date,montant,categorie,description,type_client,devise
80,1081,2024-02-26,-486.21,Loisirs,ACHAT CARREFOUR,None,CHF
81,1082,2024-03-08,-2492.99,Salaire,ACHAT CARREFOUR,particulier,CHF
82,1083,2024-02-07,1107.61,Transport,ACHAT,pro,CHF
83,1084,2024-03-02,-1515.90,Transport,ACHAT UBER,particulier,CHF
84,1085,2024-01-07,3022.01,Alimentation,ACHAT,particulier,CHF
85,1086,2024-03-11,-2017.57,Loisirs,ACHAT CARREFOUR,None,CHF

In [45]:
df.loc[90:95, 'type_client']='entreprise'# Valeur non Standardisée.

In [46]:
df.loc[90:95]

,transaction_id,date,montant,categorie,description,type_client,devise
90,1091,2024-01-19,-3344.09,???,ACHAT NETFLIX,entreprise,USD
91,1092,2024-01-09,2017.04,None,ACHAT SALAIRIE,entreprise,GBP
92,1093,2024-03-01,-3936.92,Alimentation,ACHAT,entreprise,EUR
93,1094,2024-01-20,3972.74,Salaire,ACHAT,entreprise,
94,1095,2024-02-19,-1033.94,Transport,ACHAT,entreprise,USD
95,1096,2024-03-20,2914.37,Loisirs,ACHAT NETFLIX,entreprise,EUR

In [47]:
#Afficher les notifications des resultats des traitements.
print("===APERCU DONNEES BRUTES====")
print(df.head(10))
print(f"\nTaille: {len(df)}lignes")

===APERCU DONNEES BRUTES====
   transaction_id       date  montant     categorie     description  \
0            1001 2024-01-22  1430.88          None             NaN
1            1002 2024-03-27 -2264.97       Loisirs             NaN
2            1003 2024-02-18  9134.51           ???             NaN
3            1004 2024-03-08  6326.02       Salaire             NaN
4            1005 2024-01-15 -1879.63       Loisirs      ACHAT UBER
5            1006 2024-03-05    65.66     Transport   ACHAT NETFLIX
6            1007 2024-02-23  9999.90     Transport          ACHAT
7            1008 2024-01-30  9999.90       Salaire  ACHAT SALAIRIE
8            1009 2024-01-20  9999.90  Alimentation   ACHAT NETFLIX
9            1010 2024-02-02  1000.10  Alimentation      ACHAT UBER

   type_client devise
0          pro    EUR
1  particulier    EUR
2  particulier
3  particulier    EUR
4  particulier    EUR
5         None    USD
6         None    GBP
7         None    USD
8  particulier    EUR
9          pro    EUR

Taille: 500lignes